### ISSUE TITLE
Missing Copyright & Licensing Information

### ISSUE THREAD

**Issue by ghost** [PDP-10/itstar#1]
itstar seems to be missing any sort of licensing info at all. Is it okay to change and share it? It doesn't say. Back in June 2016 I wrote to John Wilson about this. We exchanged some messages back and forth and he gave permission to place it under the GPL. I'm including a copy of his email as a way to memorialize that permission.

[Relicensing Permission.txt](https://github.com/PDP-10/itstar/files/641124/Relicensing.Permission.txt)

It seems Lars has made changes to itstar, which raises the question of what license applies to those changes? Ideally the GPL too so that everything can be consistent. I'll try to make everything as easy as possible and send a pull request to make the appropriate changes. If Lars wants to apply the GPL to his changes all that needs doing is to accept the pull request.

**Comment by larsbrinkhoff** [comment]
Thanks.  I also emailed John Wilson about this code, but didn't get any reply, so it good to hear you heard back from him.

I'm fine with GPL.
