### ISSUE TITLE
latest itstar creates tape that can't be read by ITS

### ISSUE THREAD

**Issue by eswenson1** [PDP-10/itstar#8]
I created a tape with a single file on it: system; ttytyp 319 (used the latest one from the ITS repo).  Using "itstar tvf" shows that thins look good:

```
$ itstar tvf ../xfer10.tape
Tape 1, reel 0, created 08/02/19, type=random
SYSTEM;TTYTYP 319   2019-7-2
$
```
However, trying to read this tape on EX ITS (pdp10-ka, TM10B, RH10, RP06) gives this error:
```
*dump^K!
DUMP  .445

_rewind
_list
 LIST DEV =tty
TAPE NO      1 CREATION DATE  190802

     1 SYSTEM TTYTYP 319        0      8/2/2019 16:57:00 E-O-T
 REEL =      0
_rewind
_load
FILE=system;ttytyp 319
FILE=

BAD HEADER
 E-O-T
_
```

**Comment by eswenson1** [comment]
I tried to get "around" the issue by writing a tape with more files than I needed and I got the same error on the first file read from the tape by ITS, but the remaining files were loaded fine.  So the issue seems to be with the first tape written to the tape by itstar.

**Comment by larsbrinkhoff** [comment]
Please check that you are using the latest master version, and not my
skipfile branch.  I had this problem on my branch.

**Comment by eswenson1** [comment]
I was using the skipfile branch. I thought that was the best version. I’ll go back to master branch and retry.

**Comment by larsbrinkhoff** [comment]
The problem *should* be fixed on the branch.  I'll merge it to master
when I think it's ready.

**Comment by larsbrinkhoff** [comment]
Eric, has this been resolved?

**Comment by eswenson1** [comment]
I don’t know. I’ll have to retest with your latest itstar.

**Comment by eswenson1** [comment]
Yes, this seems to work fine now with itstar from HEAD of master branch.
